### ISSUE TITLE
Allow copy output panel texts.

### ISSUE THREAD

**Issue by xpol** [noseglid/atom-build#221] opened 2015-11-10 02:29 UTC
Currently cmd+c will not work.

**Comment by noseglid** [comment] 2015-11-10 07:10
This used to be an issue, reported and fixed in #34. It seems to have stopped working again though. I have confirmed that the fix in #34 is still in place. Something else must've changed. Thanks for reporting.

**Comment by noseglid** [comment] 2015-11-19 14:52
This probably is a regression in Atom: https://github.com/atom/atom/issues/9548 I'll keep tabs on it and push to get it resolved.

**Comment by ebkalderon** [comment] 2015-11-25 19:10
Seems to work fine on my Arch box. It seems like atom/atom#9548 has been fixed. Can we close this issue now?

**Comment by xpol** [comment] 2015-11-26 07:10
@ebkalderon What version of Atom do you use? I use 1.2.3 and not fixed.

**Comment by noseglid** [comment] 2015-11-26 07:46
This works for me on the Beta channel (shasum atom/atom@f159e81), which suggests it will be fixed in `1.3.0`.

I want to keep this open until it is fixed in stable.

**Comment by xpol** [comment] 2015-12-10 01:36
1.3.0 has released.
Tested on mac, still can not copy via `cmd-c`.

**Comment by noseglid** [comment] 2015-12-10 09:11
Still not fixed. Apparently not included in `1.3.0` until 1.4.0. I'm trying to push for a minor release to get this fixed sooner.

In Beta channel this works.

**Comment by xpol** [comment] 2015-12-11 02:12
Finally, the Atom releases `1.3.1` and fixes this.
@noseglid Thanks!

**Comment by noseglid** [comment] 2015-12-11 08:44
Yea. looks like it works now. Great that we managed to get a point release for this. This has been open for too long.

**Closed by noseglid** 2015-12-11 08:44 UTC
