### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/home/zethra/atom:'

### ISSUE THREAD

**Issue by zethra** [noseglid/atom-build#318] opened 2016-02-10 03:49 UTC
Open keymap file

**Atom Version**: 1.5.0
**System**: Ubuntu 15.10
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.54.1

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/home/zethra/atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat '/home/zethra/atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at /home/zethra/.atom/packages/build/lib/build.js:127:27
    at Array.find (native)
    at Object.activePath (/home/zethra/.atom/packages/build/lib/build.js:126:74)
    at Object.updateStatusBar (/home/zethra/.atom/packages/build/lib/build.js:133:49)
    at /home/zethra/.atom/packages/build/lib/build.js:68:57
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:327:21)
    at atom-tabs.TabBarView.onMouseDown (/usr/share/atom/resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:670:19)
```

### Commands

```
     -7:46.8.0 tool-bar:toggle (div.tool-bar.tool-bar-top.tool-bar-horizontal.tool-bar-24px)
     -6:25.3.0 terminal-plus:toggle (atom-text-editor.editor.mini.is-focused)
     -5:11.9.0 core:paste (atom-text-editor#terminal-plus.style.fontFamily.editor.mini.is-focused)
 11x -5:08.8.0 terminal-plus:toggle (div.package-detail.panels-item)
     -4:42.2.0 core:backspace (atom-text-editor#terminal-plus.style.animationSpeed.editor.mini.is-focused)
     -4:40.9.0 core:confirm (atom-text-editor#terminal-plus.style.animationSpeed.editor.mini.is-focused)
 14x -4:38.7.0 terminal-plus:toggle (div.package-detail.panels-item)
     -4:09.8.0 core:backspace (atom-text-editor#terminal-plus.style.defaultPanelHeight.editor.mini.is-focused)
 11x -4:08.5.0 terminal-plus:toggle (div.package-detail.panels-item)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "packagesWithKeymapsDisabled": []
  }
}
```

### Installed Packages

```coffee
# User
build, v0.54.1
color-picker, v2.1.1
language-ini, v1.14.0
linter, v1.11.3
linter-gcc, v0.6.5
minimap, v4.19.0
pigments, v0.23.1
platformio-ide, v0.3.3
platformio-ide-terminal, v1.15.1
terminal-plus, v0.14.5
tool-bar, v0.2.0

# Dev
No dev packages
```

**Comment by noseglid** [comment] 2016-02-10 07:27
Dupe of #273

**Closed by noseglid** 2016-02-10 07:27 UTC
