### ISSUE TITLE
Rust Build Not Working on Windows

### ISSUE THREAD

**Issue by excaliburHisSheath** [noseglid/atom-build#44] opened 2015-03-05 02:54 UTC
Building a rust project on windows still tries to use sh. This also breaks custom build configurations since the built in one seems to override the custom options.

**Comment by noseglid** [comment] 2015-03-05 07:34
Thanks for the report! It really should not use sh on windows!

However, custom options (e.g. a `.atom-build.json` file in the tree root) should be prioritized over any built-in tool. Could you detail your file structure?

**Comment by excaliburHisSheath** [comment] 2015-03-05 18:02
I have the following `.atom-build.json`:

```
{
    "cmd": "cargo",
    "args": ["build"],
    "sh": false
}
```

When I try to build I get the following error and stack trace:

```
TypeError: Cannot read property 'sh' of undefined
  at ChildProcess.<anonymous> (C:\Users\excaliburhissheath\.atom\packages\build\lib\build.js:245:38)
  at ChildProcess.emit (events.js:116:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1070:12)
  at child_process.js:1142:20
  at process._tickCallback (node.js:364:11)
```

**Comment by noseglid** [comment] 2015-03-05 20:38
I think that is a duplicate of #45 . I'll publish a new version soon with it (and this) fixed.

**Closed** 2015-03-05 20:41 UTC
Labels: bug

**Comment by excaliburHisSheath** [comment] 2015-03-06 15:35
Cool, sorry for the duplicate.
