### ISSUE TITLE
Crash when saving .atom-build.json

### ISSUE THREAD

**Issue by cwaffles** [noseglid/atom-build#277] opened 2016-01-08 22:07 UTC
Hi,

Whenever I save my .atom-build.json file, it crashes/freezes the atom editor. Sometimes I don't get the warning dialogue, but it shows up 9/10 times. The actual builds work fine, since the file is saved before it crashes.

![screenshot at 2016-01-08 14 02 58](https://cloud.githubusercontent.com/assets/3838856/12210688/a834f548-b610-11e5-9039-85270b8e0398.png)

System: Linux Mint 17.3 x64 MATE
Atom version 1.3.2
All community plugins disabled
Config file: http://pastebin.com/DqsuBDpn

**Comment by C-Bouthoorn** [comment] 2016-01-08 22:38
Confirmed in Linux 4.2.0-23 Ubuntu 64 bit   Atom 1.4.0-beta2

**Comment by noseglid** [comment] 2016-01-10 09:01
That is weird. I guess it has something to do with the filewatcher being used which is supposed to update the targets when the file is changed. Does it work if it is edited with another editor, or does it crash then as well? It should be enough to just `touch` the file on linux.

**Comment by cwaffles** [comment] 2016-01-10 18:27
When editing the .atom-build.json file in another editor, there is no crash, and the build plugin gives me the blue notification in the top right corner of my screen that the targets are found.

**Comment by noseglid** [comment] 2016-01-10 21:02
I see. This doesn't seem to be reproducible on OS X (which I mainly work on). Did you try reporting to `atom/atom` as suggested?

**Comment by C-Bouthoorn** [comment] 2016-01-11 16:44
Okay, so when I change the .atom-build.json file in another editor (nano), Atom _does_ crash.

When running in dev mode (`atom-beta -d -f -w`), I get

`[14971:0100/000000:WARNING:ipc_channel_posix.cc(824)] Message needs unreceived descriptors channel:0x2119ddc9b600 message-type:1704264 header()->num_fds:1`

Editing the file with Build disabled gives no message, and Atom doesn't crash.

**Comment by C-Bouthoorn** [comment] 2016-01-11 16:50
Update:

Changing `() => this.emit('refresh')` to `() => console.log("Hello")` on line 62 in atom-build.js stopped the error from coming. Doing further checks.

**Comment by noseglid** [comment] 2016-01-11 19:10
Thank you for investiaging. Using `fs.watchFile` works on OS X. However, I suspect there may be some race condition going on here which probably is not fixed by this change. I guess the weird thing is that it `fs.watch` seem to trigger even though the file is only altered once.

When 'refresh' is emitted from `atom-build.js`, `build.js` will remove all listeners for refresh, and then re-register. Why is `fs.watch` triggered at this point? Could it be that `fs.watch` touches the file or something (seems unlikely)?

**Comment by C-Bouthoorn** [comment] 2016-01-11 19:28
I think it's the case in Linux (So not OS X or Windows) that closing a file descriptor (Or a watcher in this case) actually changes some data about the file, again triggering a change. This would be fixed by having 1 watcher, and only closing that when you close the program, but you're currently reopening the watcher every time the file changes, so that might be the case of the problem.

I've found [here](http://stackoverflow.com/a/12979775/4141219) (with a link to [NodeJS's own docs](https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener)) that `fs.watch` is unstable, but I also found that `fs.watchFile` is even worse.

A cleaner approach would be to have only one watcher per file as I mentioned before, but I don't have any idea how to implement that. In the meantime, `fs.watchFile` is a dirty fix, but it works for me.

**Comment by noseglid** [comment] 2016-01-11 19:34
I can't see any drawback of changing to `fs.watchFile` at this point. The docs even say `You can still use fs.watchFile, which uses stat polling, but it is slower and less reliable.`.

So if you create a PR for that I'd be happy to merge!

**Comment by C-Bouthoorn** [comment] 2016-01-11 20:17
@noseglid Did you get a notification? Not yet sure how Github handles these things

**Comment by noseglid** [comment] 2016-01-12 07:48
Yes, I commented on the PR. Some tests failed but should be easy fix.

**Comment by Calrama** [comment] 2016-03-20 16:03
I encountered the same problem with Atom seemingly entering an infinite loop on saving any .atom-build.{json,cson,yml}. I applied the changes from the PR and now it works fine.

**Comment by noseglid** [comment] 2016-03-20 19:42
@Calrama do you have a reliable way to reproduce?

**Comment by Calrama** [comment] 2016-03-21 02:25
@noseglid Are you referring to encountering the issue or the workaround? In any case, it happens to me on a Funtoo Linux x86_64 current system every time I do this:
1. Start Atom 1.5.4 with this package (latest available via Atom's package installer) enabled (all third-party packages disabled)
2. Open a folder (in my case the root folder of a D project)
3. Out of the three possible files .atom-build.{yml,json,cson}, write to the one atom-build has loaded for this folder from anywhere.
4. Atom goes crazy in CPU cycles (OT: dropping 8 hours of projected battery time to about 2 hours) and needs to be `kill`ed
As I wrote above, after applying the PR's changes, that issue does not happen anymore.

**Comment by noseglid** [comment] 2016-03-21 07:53
I'm a bit reluctant to change to the `watchFile` implementation without know *how* it fixes the issue. Primarily because NodeJS's documentation states
> Note: fs.watch() is more efficient than fs.watchFile and fs.unwatchFile. fs.watch should be used instead of fs.watchFile and fs.unwatchFile when possible.

And also because it breaks another feature (clearing the cache of the build file), see #281 for details on this.

Maybe it's possible to work around it? I would certainly be open to suggestions!

**Comment by C-Bouthoorn** [comment] 2016-03-21 14:35
As this seems to work fine the way it is on Windows and Macintosh, and it works fine with this change on Linux, I suppose we should add an os-check somewhere, and choose the right function. I guess there should be a way to clean the cache on Linux too, but I/we will have to search how.

On Mon, Mar 21, 2016 at 8:53 a.m., Alexander Olsson <notifications@github.com> wrote:
I'm a bit reluctant to change to the watchFile implementation without know how it fixes the issue. Primarily because NodeJS's documentation states

Note: fs.watch() is more efficient than fs.watchFile and fs.unwatchFile. fs.watch should be used instead of fs.watchFile and fs.unwatchFile when possible.

And also because it breaks another feature (clearing the cache of the build file), see #281 [https://github.com/noseglid/atom-build/pull/281] for details on this.

Maybe it's possible to work around it? I would certainly be open to suggestions!

**Comment by noseglid** [comment] 2016-03-21 14:40
@C-Bouthoorn I think you're right. If we can solve the caching issue we could use `watchFile` on windows instead.

**Comment by C-Bouthoorn** [comment] 2016-03-21 15:04
*Update*: What about [watchr](https://www.npmjs.com/package/watchr) ? It seems to do this job nicely

**Comment by Calrama** [comment] 2016-03-21 19:01
> I'm a bit reluctant to change to the watchFile implementation without know how it fixes the issue. Primarily because NodeJS's documentation states

I did not mean to imply that it should be adopted. My main concern was to confirm this workaround for people who run into it.

> And also because it breaks another feature (clearing the cache of the build file)

I read that before posting here initially, though unfortunately I did not understand it.

> Have we tried editing the .atom-build file with another editor of which we know does not backup anything?

Yes, with 
> write to the one atom-build has loaded for this folder.

I meant regardless of how. Be that nano, vi, cat/echo stdout redirect. Doesn't matter. Any write to the file causes it for me.

> What about watchr ? It seems to do this job nicely

I will try this change asap.

**Comment by C-Bouthoorn** [comment] 2016-03-21 19:37
@Calrama 

> I will try this change asap.

I'm actually trying to implement `watchr` in https://github.com/noseglid/atom-build/pull/353 so if you would like to contribute, that's the place.

**Comment by Calrama** [comment] 2016-03-23 21:55
> I'm actually trying to implement watchr in #353 so if you would like to contribute, that's the place.

Finally had the time to check it out: Works fine for me on Linux (git clone your repo + apm install), no freezes or crashes. :+1:

**Comment by noseglid** [comment] 2016-03-30 16:48
I think I've fixed the issue with caching in #372. ping @C-Bouthoorn Can you check if this works in your environment?

For reference, it wasn't really an issue with caching, but rather the tests. Since the targets are refreshed asynchronously, there's nothing to watch for to see when this is done. The tests just waited an arbitrary time. Since `watchFile` polls it is slower than `watch` thus causing the issues. I've changed so it waits for the notification instead.

**Comment by noseglid** [comment] 2016-04-01 06:33
@C-Bouthoorn @Calrama @cwaffles Have any of you had a chance to test the fix in #372 ?

**Comment by Calrama** [comment] 2016-04-01 20:34
Sorry about the delay. LGTM (no crashes or freezes for me).

**Comment by C-Bouthoorn** [comment] 2016-04-02 13:31
Going to test now.

**Closed** 2016-04-03 06:51 UTC
Labels: bug
