### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Jakub\AppData\Local\atom\app-1...

### ISSUE THREAD

**Issue by DevilSauron** [noseglid/atom-build#275] opened 2016-01-01 22:10 UTC
Build and build-cargo installed

1. ... Start atom.io or try to build
2. ... ERROR

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.52.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\Jakub\AppData\Local\atom\app-1.3.2\atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'C:\Users\Jakub\AppData\Local\atom\app-1.3.2\atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at C:/Users/Jakub/.atom/packages/build/lib/build.js:217:27
    at Array.find (native)
    at Object.activePath (C:/Users/Jakub/.atom/packages/build/lib/build.js:216:74)
    at Object.updateStatusBar (C:/Users/Jakub/.atom/packages/build/lib/build.js:223:49)
    at C:/Users/Jakub/.atom/packages/build/lib/build.js:158:57
    at Emitter.module.exports.Emitter.emit (C:\Users\Jakub\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\Jakub\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane-container.js:333:27
    at Emitter.module.exports.Emitter.emit (C:\Users\Jakub\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\Jakub\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\Jakub\AppData\Local\atom\app-1.3.2\resources\app.asar\src\pane.js:316:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\Jakub\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:670:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "D:\\Programování\\Projekty",
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "build": {}
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.10
atom-material-ui, v0.8.0
build, v0.52.0
build-cargo, v0.11.0
color-picker, v2.0.14
editorconfig, v1.2.2
file-icons, v1.6.13
highlight-selected, v0.11.1
language-rust, v0.4.5
linter, v1.11.3
linter-rubocop, v0.4.6
linter-rust, v0.3.0
minimap, v4.19.0
pigments, v0.19.5
terminal-plus, v0.14.5
tool-bar, v0.1.9
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by noseglid** [comment] 2016-01-02 08:15
Dupe of #273

**Closed by noseglid** 2016-01-02 08:15 UTC
