### ISSUE TITLE
Uncaught Error: kill EINVAL

### ISSUE THREAD

**Issue by oli-obk** [noseglid/atom-build#78] opened 2015-05-20 09:23 UTC
I exepected either a comprehensible error or arbitrary order application of the environment variables

1. add the same environment variable twice to `.atom-build.json`
2. build

**Atom Version**: 0.200.0
**System**: Unknown Windows Version
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.33.0

### Stack Trace

Uncaught Error: kill EINVAL

```
At child_process.js:1220

Error: kill EINVAL
  at exports._errnoException (util.js:734:11)
  at ChildProcess.kill (child_process.js:1220:13)
  at Object.module.exports.abort (C:\Users\ca8159\.atom\packages\build\lib\build.js:276:16)
  at Object.<anonymous> (C:\Users\ca8159\.atom\packages\build\lib\build.js:285:14)
  at saveAndContinue (C:\Users\ca8159\.atom\packages\build\lib\build.js:297:7)
  at Object.module.exports.doSaveConfirm (C:\Users\ca8159\.atom\packages\build\lib\build.js:301:14)
  at Object.module.exports.build (C:\Users\ca8159\.atom\packages\build\lib\build.js:283:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\ca8159\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\ca8159\AppData\Local\atom\app-0.200.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\ca8159\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\ca8159\AppData\Local\atom\app-0.200.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\ca8159\AppData\Local\atom\app-0.200.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Commands

```
     -0:59.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:58.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:56.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:53.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:52.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
 13x -0:51.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:48.5.0 core:copy (atom-text-editor.editor.is-focused)
  3x -0:47.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:41.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:37.5.0 build:trigger (atom-text-editor.editor.is-focused)
     -0:10.7.0 core:copy (atom-text-editor.editor.is-focused)
     -0:09.8.0 core:paste (atom-text-editor.editor.is-focused)
     -0:08.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:05.8.0 build:trigger (atom-text-editor.editor.is-focused)
  2x -0:03.0 core:undo (atom-text-editor.editor.is-focused)
     -0:00.8.0 build:trigger (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete-plus",
      "language-ruby-on-rails",
      "background-tips"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "build": {
    "saveOnBuild": true,
    "minimizedHeight": 0.25,
    "panelVisibility": "Keep Visible"
  }
}
```

### Installed Packages

```coffee
# User
build, v0.33.0
git-log, v0.3.0
language-rust, v0.4.3
linter, v0.12.4
linter-rust, v0.0.13
minimap, v4.9.0
project-manager, v1.15.5
racer, v0.11.0
save-session, v0.15.1
trailing-spaces, v0.2.5

# Dev
No dev packages
```

**Comment by noseglid** [comment] 2015-05-24 09:32
I am not able to reproduce this on OS X. Could this be a Windows issue? Haven't tested on Linux.

There has been some changes on how the environment variables are handled and replaced. Could you re-test with latest version (`v0.35.0`) ?

**Comment by oli-obk** [comment] 2015-05-26 07:17
still happening on `v0.35.0`. But I have noticed that if all instances of the env-var have the same value, no error occurs. My use case was a readable `PATH` setting, instead of everything in one line.

```json
    "PATH": "C:\\Program Files\\Rust stable 1.0\\bin;%PATH%",
    "PATH": "bin\\x86_64-pc-windows-gnu;%PATH%",
```

**Comment by noseglid** [comment] 2015-05-26 08:32
Why are you using multiple entries of the same variable? Was this just an error, or do you have a real use case for it?

**Comment by oli-obk** [comment] 2015-05-26 08:37
My use case is making the `.atom-build.json` readable with long `PATH` variables. My `PATH` variable was getting very long, so I wanted to split it up.

**Comment by noseglid** [comment] 2015-05-26 08:49
Oh I see. I don't think that would work anyway since `atom-build` can only pass one variable of each key to the spawn command. I think your best course of action for now is to simply have one long row.

There should be a fix for this so it doesn't throw EINVAL anway. I'll look into this.

**Closed** 2015-06-10 19:40 UTC
