### ISSUE TITLE
Linter shortcut not taking cursor to offending line

### ISSUE THREAD

**Issue by skull132** [noseglid/atom-build#364] opened 2016-03-27 14:50 UTC
With the new Linter integration, I've noticed that clicking the shortcuts displayed by Linter only opens the offending file, and will not take my cursor to the specific line marked. As opposed to cycling through with F-4, which works as intended and does move my cursor.

Note that I am using a compiler which does not output an offending column, simply the file and line. Since I don't use build for anything that does put out a column value, I cannot test whether or not this issue only occurs when the column value is missing.

Example error that Linter offers up: `Error from build at line 340 col NaN in code\modules\admin\admin_verbs.dm`

**Comment by noseglid** [comment] 2016-03-27 20:21
Thanks for reporting.

Could you provide me with the error matching regex, and a sample output so I can try and reproduce?

**Comment by skull132** [comment] 2016-03-27 20:27
Regex: `"\n(?<file>[\\\\\/0-9a-zA-Z\\._ ]+):(?<line>\\d+):error"`

Output generated into the build/compile panel:
```
loading baystation12.dme
loading interface\skin.dmf
code\modules\cciaa\cciaa.dm:173:error: isb: undefined proc
baystation12.dmb - 1 error, 0 warnings (3/27/16 11:24 pm)
```

**Comment by noseglid** [comment] 2016-03-27 20:40
That was sloppy. Since only `file` is required in the errorMatcher, it should handle this better. I've pushed a fix to a branch where it defaults to col 1 if column is missing and row 1 if row is missing.

Thanks for reporting. This will be in the next release.

**Comment by noseglid** [comment] 2016-03-27 20:56
Also quick pro-tip: add `: (?<message>.*)` to your regex (so it becomes `(?<file>[\\/0-9a-zA-Z\\._ ]+):(?<line>\\d+):error: (?<message>.*)` and you will also get the message in the linter panel :)

**Comment by skull132** [comment] 2016-03-27 21:02
I was actually wondering if such shenaniganry was already a thing or not.

Thank you, for both the quick response and the tip.

**Closed** 2016-03-28 07:22 UTC
