### ISSUE TITLE
emitter.prependListener is not a function

### ISSUE THREAD

**Issue by alex94puchades** [noseglid/atom-build#438] opened 2016-06-03 00:28 UTC
Building project doesn't work anymore, shows "Build error: emitter.prependListener is not a function".
Atom version is 1.7.4, with atom-build version 0.64.0.

**Comment by noseglid** [comment] 2016-06-03 06:19
Please try and restart Atom. If that doesn't work re-install atom-build. If *that* doesn't work please include more information. Like what are you doing? What are you trying to build.

Generally you should _always_ include steps to reproduce if you expect any help resolving your issues.

**Comment by alex94puchades** [comment] 2016-06-03 12:25
Hi, sorry for the vague report, I didn't thought I was the only one with this issue. I tried restarting and reinstalling with no luck. The error shows every time I trigger a build (F7 or F9 makes no difference), the build takes forever and when I manually close the bottom-panel I can no longer trigger another build. [Here](http://s33.postimg.org/k3di7pxpb/atom_build_issue.png) is an screenshot of the error I get.

Originally I was trying to build a CMake-based project, but the issue is present also in Makefile projects.

**Comment by alex94puchades** [comment] 2016-06-06 22:01
@noseglid: have you confirmed this? Can I help you any further?

**Comment by noseglid** [comment] 2016-06-07 07:36
No, I still have no way of reproducing this.
Can you create a minimal `.atom-build.yml` reproducing this issue and include steps how to get this error?

**Comment by alex94puchades** [comment] 2016-06-08 21:09
I tried the test `.atom-build.yml` in the README, now I get a "No eligible build target" warning (maybe related to #230?). I am running atom in fedora 24 from [this repo](https://copr.fedorainfracloud.org/coprs/mosquito/atom/) if that helps (might be a version mismatch?)

**Comment by noseglid** [comment] 2016-06-09 06:32
What folder did you put `.atom-build.yml` in and how do you open Atom?

**Comment by alex94puchades** [comment] 2016-06-09 06:57
I'm sorry, no clue what changed but now it worked :confused: I get same error as before ("Build error: emitter.prependListener is not a function"). `.atom-build.yml` is below:

```yaml
cmd: echo Foo
```

**Comment by noseglid** [comment] 2016-06-09 07:01
What version of Atom are you running?

**Comment by alex94puchades** [comment] 2016-06-09 07:01
atom v1.7.4

**Comment by noseglid** [comment] 2016-06-09 07:22
Some quick googling suggests this *may* be an [issue in node](https://github.com/nodejs/node/issues/6405), but that just seems to be the benchmark.

However, `prependListener` was [added in node 6.0.0](https://nodejs.org/en/blog/release/v6.0.0/).
There's [no code in atom-build which invokes `prependListener`](https://github.com/noseglid/atom-build/search?utf8=%E2%9C%93&q=prependListener), so it must be coming from somewhere else. (My Atom 1.8.0 is running node `v5.1.1`.

**Comment by alex94puchades** [comment] 2016-06-12 13:31
Running `find ~/.atom/packages -type f -name "*.js" -exec grep -H prependListener {} \;` only lists `readable-stream` (a deep dependency of the `sync-settings` package) as calling prependListener (despite [feature-checks](https://github.com/nodejs/readable-stream/blob/master/lib/_stream_readable.js#L58) being made) and uninstalling it solved the issue. I'll report it. Thanks for your help!

**Comment by noseglid** [comment] 2016-06-12 13:32
Cool. I'm glad it worked out!

**Comment by alex94puchades** [comment] 2016-06-12 13:32
I forgot, the prependListener error is unrelated, but the original issue remains :sweat:

**Comment by noseglid** [comment] 2016-06-12 13:34
Wasn't the original issue about `prependListener` ?

**Comment by alex94puchades** [comment] 2016-06-12 13:37
Sorry, atom-build stopped working at the same time `prependListener` errors started, so I thought they were related. Would it be better to open another issue? or just rename this one..

**Comment by noseglid** [comment] 2016-06-12 13:38
Open a new one.

**Closed by noseglid** 2016-06-12 13:38 UTC
