### ISSUE TITLE
Col should be 0 by default

### ISSUE THREAD

**Issue by averrin** [noseglid/atom-build#368] opened 2016-03-29 16:24 UTC
go build output:
```
# command-line-arguments
./runner.go:51: undefined: R in R.History
```

my errorMatch rule:
```
"(?<file>[\/0-9a-zA-Z\\._]+):(?<line>\\d+): (?<message>.+)"
```

Linter message:
```
undefined: R in R.History at line 51 col NaN in ./runner.go
```
And click on it open file, but didnt go to line.

Imho, line and col should be zero if not defined.

**Comment by noseglid** [comment] 2016-03-29 18:17
Dupe of #364

**Closed by noseglid** 2016-03-29 18:17 UTC
