### ISSUE TITLE
Failed to load the build package

### ISSUE THREAD

**Issue by saswatds** [noseglid/atom-build#110] opened 2015-06-26 21:22 UTC
[Enter steps to reproduce below:]

1. Setting> Install > Search build
2. Install

**Atom Version**: 1.0.0
**System**: Microsoft Windows 8.1 Single Language
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.38.0

### Stack Trace

Failed to load the build package

```
At Cannot find module 'bluebird'

Error: Cannot find module 'bluebird'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\user\.atom\packages\build\lib\build.js:4:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:709:34)
  at C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:188:28
  at Package.module.exports.Package.measure (C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
  at Package.module.exports.Package.load (C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:179:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:372:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:451:30)
  at C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:362:29
  at exit (C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:53:16)
  at triggerExitCallback (C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:213:47)
  at ChildProcess.<anonymous> (C:\Users\user\AppData\Local\atom\app-1.0.0\resources\app.asar\src\buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
 22x -6:49.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -6:39.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "base16-tomorrow-light-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
build, v0.38.0
terminal-panel, v1.14.1

# Dev
No dev packages
```

**Comment by noseglid** [comment] 2015-06-27 06:38
Weird. Bluebird is specified as a dependency and should be installed by `apm` when the package is installed. Could you try to
```shell
apm uninstall build
apm install build
```

**Comment by noseglid** [comment] 2015-07-01 18:58
Closing this out. Please come back if the issue persists.

**Closed by noseglid** 2015-07-01 18:58 UTC

**Comment by Rainrider** [comment] 2015-08-26 13:40
Don't know it this is the right place to post this but the atom error tool points here. I already re-installed the build package, error still persists.

[Enter steps to reproduce below:]

1. Open a folder in Atom from the context menu
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 10 Pro
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.44.0


### Stack Trace

Failed to load the build package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\user\AppData\Local\atom\app-1.0.7\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\user\.atom\packages\atom-build\lib\build.js:7:9)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\user\AppData\Local\atom\app-1.0.7\resources\app.asar\src\babel.js:167:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "omnisharp-atom"
    ]
  },
  "build": {}
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
build, v0.44.0
language-lua, v0.9.4
language-pascal, v0.7.0
language-textile, v0.2.0
line-ending-converter, v1.3.2
linter, v1.4.3
linter-lua, v1.0.0
wordcount, v2.3.0

# Dev
No dev packages
```

**Comment by noseglid** [comment] 2015-08-27 06:00
Can you update to the latest version and try again?

**Comment by Rainrider** [comment] 2015-08-27 09:14
Same with the latest version. I downloaded the zip from github, extracted into the .atom/packages folder and changed the name to atom-build. If I shall re-install in another way please tell me.

**Comment by noseglid** [comment] 2015-08-27 10:34
Hmm. You should definitely use the built-in package manager. The latest version doesn't use bluebird at all. Also, it will automatically install all the dependencies- which is probably what you missed

**Comment by Rainrider** [comment] 2015-08-27 11:34
The latest version I get though the build-in package manager is 0.44.0, that is also the version that caused the error I posted. Also, it complains about `lodash` not about bluebird.

**Comment by noseglid** [comment] 2015-08-27 13:18
Yea.. When you unzip the package it doesn't install the dependencies. You would have to run 'apm install' or re-install via the package manager. I'd recommend the latter.

**Comment by Rainrider** [comment] 2015-08-27 19:38
I did re-install via the package manager prior to posting the report. The
error came from a fresh install of 0.44.0.

**Comment by noseglid** [comment] 2015-08-28 05:53
Then you should probably report the error over at atom/apm. The logic for installing dependencies is not part of a package.

**Comment by dobosgy** [comment] 2015-11-22 12:49
1. Starting Atom
2. Error message on the top right corner

**Atom Version**: 1.2.2
**System**: Ubuntu 14.04.3
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.49.1


### Stack Trace

Failed to load the build package

```
At Cannot find module 'XRegExp'

Error: Cannot find module 'XRegExp'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/dobosgy/.atom/packages/build/lib/error-matcher.js:4:24)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "exception-reporting",
      "feedback",
      "git-diff",
      "language-c",
      "language-gfm",
      "language-git",
      "language-go",
      "language-java",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "language-yaml",
      "open-on-github",
      "run-command",
      "remote-edit"
    ],
    "themes": [
      "one-light-ui",
      "own-fizzy"
    ],
    "fileEncoding": "iso88592"
  },
  "build": {}
}
```

### Installed Packages

```coffee
# User
build, v0.49.1
color-picker, v2.0.13
file-types, v0.5.1
highlight-selected, v0.11.1
less-autocompile, v1.0.0
minimap, v4.16.1
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.1
own-fizzy, v0.15.0
project-manager, v2.6.5
remote-sync, v3.5.0
tablr, v0.7.0
tool-bar, v0.1.9
tool-bar-main, v0.0.8

# Dev
No dev packages
```

**Comment by C-Bouthoorn** [comment] 2015-11-22 12:54
For me the same error as @dobosgy above. Running Ubuntu 15.10. I did try

```sh
$ sudo npm install xregexp
xregexp@3.0.0 node_modules/xregexp
$ sudo apm install xregexp
Installing xregexp to /home/charlie/.atom/packages ✗
Request for package information failed: Not Found
```

But the error didn't disappear. I did restart Atom.

**Comment by noseglid** [comment] 2015-11-22 20:21
This was a new regression. Fixed in `v0.49.2`.

**Comment by aisotton** [comment] 2016-03-21 22:54
This seems to happen again with atom 1.6.0 and 0.57.0.

Cannot find module 'tree-kill'
Hide Stack Trace
Error: Cannot find module 'tree-kill'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/aaronisotton/.atom/packages/build/lib/build.js:4:55)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)

**Comment by C-Bouthoorn** [comment] 2016-03-22 06:55
Restarting Atom should work

**Comment by noseglid** [comment] 2016-03-22 07:20
Or re-installing atom.

**Comment by perezperret** [comment] 2016-07-04 14:06
I'm being redirected to this issue, I just installed Atom on OS X 10.11.5, I'm being referenced to this issue. The editor seems to be working properly but I keep getting a warning. Here's the full trace


```
Cannot read property 'prototype' of undefined
Hide Stack Trace
TypeError: Cannot read property 'prototype' of undefined
    at __extends (<anonymous>:1:1)
    at <anonymous>:6:3
    at Object.<anonymous> (<anonymous>:6:3)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (<anonymous>:9:13)
    at Object.<anonymous> (<anonymous>:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:402:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:397:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:743:28
```
