### ISSUE TITLE
Automatically error match upon build error

### ISSUE THREAD

**Issue by jhasse** [noseglid/atom-build#87] opened 2015-05-28 20:01 UTC
When a build fails, the first thing I do is pressing Ctrl+Alt+h. Would be great if there was an option (or the default - I wouldn't mind) to always scroll to the first error when a build fails.

**Comment by noseglid** [comment] 2015-05-28 20:03
This is a duplicate of #49

**Comment by jhasse** [comment] 2015-05-28 20:40
No, I'm not talking about the build panel ;) Sorry if my English isn't that good to explain what I mean.

**Comment by noseglid** [comment] 2015-05-29 05:46
Yes, that issue also is in regard to the build panel. The TextEditor already scrolls to the code.

**Comment by jhasse** [comment] 2015-05-29 10:21
Automatically when my build fails? Without pressing Ctrl+Alt+h? It doesn't for me.

**Comment by noseglid** [comment] 2015-05-29 12:57
Now I see, you want it to autmatically jump to the error everytime it fails to build? That's not a bad idea and is indeed not a duplicate. I'll reopen this.

**Comment by jhasse** [comment] 2015-05-29 13:39
Exactly! Thanks for reopining and sorry for me being not clear enough about what I mean.

**Comment by 5n8ke** [comment] 2015-06-04 09:09
Added this feature in #90 
Default config is set to false

**Closed** 2015-06-07 14:07 UTC
