### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\aplb\AppData\Local\atom\app-1....

### ISSUE THREAD

**Issue by bottiger** [noseglid/atom-build#282] opened 2016-01-12 09:21 UTC
[Enter steps to reproduce below:]

1. Install atom-build
2. Open a file

I suspect this is a generic Windows 7 (64 bit) error

**Atom Version**: 1.3.3
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [build](https://github.com/noseglid/atom-build) package, v0.52.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat 'C:\Users\aplb\AppData\Local\atom\app-1.3.3\atom:'

```
At ATOM_SHELL_ASAR.js:0

Error: ENOENT: no such file or directory, lstat 'C:\Users\aplb\AppData\Local\atom\app-1.3.3\atom:'
    at Error (native)
    at fs.lstatSync (fs.js:844:18)
    at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:189:16)
    at Object.realpathSync (fs.js:1454:21)
    at Object.fs.realpathSync (ATOM_SHELL_ASAR.js:262:29)
    at C:/Users/aplb/.atom/packages/build/lib/build.js:217:27
    at Array.find (native)
    at Object.activePath (C:/Users/aplb/.atom/packages/build/lib/build.js:216:74)
    at Object.updateStatusBar (C:/Users/aplb/.atom/packages/build/lib/build.js:223:49)
    at C:/Users/aplb/.atom/packages/build/lib/build.js:158:57
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\aplb\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\aplb\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\aplb\AppData\Local\atom\app-1.3.3\resources\app.asar\src\pane-container.js:333:27
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\aplb\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\aplb\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Pane.module.exports.Pane.setActiveItem (C:\Users\aplb\AppData\Local\atom\app-1.3.3\resources\app.asar\src\pane.js:248:22)
    at Pane.module.exports.Pane.activateItem (C:\Users\aplb\AppData\Local\atom\app-1.3.3\resources\app.asar\src\pane.js:316:21)
    at atom-tabs.TabBarView.onMouseDown (C:\Users\aplb\AppData\Local\atom\app-1.3.3\resources\app.asar\node_modules\tabs\lib\tab-bar-view.js:670:19)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
build, v0.52.0
build-cargo, v0.12.0
language-rust, v0.4.5
racer, v0.17.2

# Dev
No dev packages
```

**Comment by noseglid** [comment] 2016-01-12 09:26
Do you have a root project open?

**Comment by noseglid** [comment] 2016-01-12 09:32
Also, this is a dupe of #273 please continue discussion in there.

**Closed by noseglid** 2016-01-12 09:32 UTC
