### ISSUE TITLE
Problem with windows path

### ISSUE THREAD

**Issue by LukasMa** [noseglid/atom-build#443] opened 2016-06-14 12:27 UTC
I can't tell if this problem is directly related to atom-build but maybe someone encountered the same problem.

I try to build a GO application with a custom build command:
`
{
  "cmd": "$GOROOT/bin/go run {FILE_ACTIVE}",
  "shell": true,
  "env": {
    "GOROOT": "C:/Program Files (x86)/Go",
    "GOPATH": "C:/GoRoot"
  }
}
`

But this will fail with the message (german): 
**Der Befehl "C://Program" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.**
Translates into english: **Command "C://Program" not found**

So the whitespaces in the path break the execution of the build command. Is there a way to use the above path or do I need to change my GO installation dir?

**Comment by noseglid** [comment] 2016-06-14 12:43
Duplicate of #432

**Closed by noseglid** 2016-06-14 12:43 UTC
