### ISSUE TITLE
Target Manager fails on Target Refresh with Atom 1.21.0 beta

### ISSUE THREAD

**Issue by wendlers** [noseglid/atom-build#541] opened 2017-09-27 20:06 UTC
Hi, 

today I tried my build providers (`scons`, `mbed`) with Atom 1.21.0 beta with ` build` 0.68.0. For both, I get an exception when the build package comes to the point where it tries to refresh targets (see below). The issue could be trigered by adding a new project folder or by calling `Build: Refresh Targets`. I also tried with the`build-make`, same thing. I looked into the code, but it is not obvious to me what the problem is. 

Also I know it might be too early to investigate that issue since 1.21.0 is still beta. Just though it might be good to be aware of this.

Regards,
Stefan

```
Cannot read property 'split' of undefined
Hide Stack Trace
TypeError: Cannot read property 'split' of undefined
    at Object.humanizeEventName (/usr/share/atom-beta/resources/app/node_modules/underscore-plus/lib/underscore-plus.js:196:29)
    at extractDescriptor (/usr/share/atom-beta/resources/app/src/command-registry.js:447:74)
    at new SelectorBasedListener (/usr/share/atom-beta/resources/app/src/command-registry.js:414:29)
    at CommandRegistry.addSelectorBasedListener (/usr/share/atom-beta/resources/app/src/command-registry.js:163:36)
    at CommandRegistry.add (/usr/share/atom-beta/resources/app/src/command-registry.js:152:25)
    at /home/stefan/dev/atom-beta/packages/build/lib/target-manager.js:113:54
    at Array.forEach (native)
    at /home/stefan/dev/atom-beta/packages/build/lib/target-manager.js:108:18
```

**Comment by wendlers** [comment] 2017-09-27 20:10
Oh, just realized, that this seams to be a duplicate of #532.

**Comment by noseglid** [comment] 2017-10-02 17:59
dupe of #532

**Closed by noseglid** 2017-10-02 17:59 UTC

**Comment by wendlers** [comment] 2017-10-04 20:06
Thanks for fixing. Works nicely now :-)
