### ISSUE TITLE
Specify build panel behavior per-command

### ISSUE THREAD

**Issue by excaliburHisSheath** [noseglid/atom-build#476] opened 2016-10-01 16:17 UTC
As discussed in AtomBuild/atom-build-cargo#64, it is sometimes desirable to have the build panel behave differently for different build commands. In my current case, the compiler emits JSON formatted messages, so when building I don't want the build panel to open, the linter output is more human-readable. But when running the project I want the output of my running program to be visible in the build window.

To achieve this, it would be nice to be able to specify per-build command how the build panel should behave. That would allow me to say "don't show the build panel when compiling, but show the build panel when running".

An alternative solution would be to have a "manual" setting for the build panel. Currently, all the settings for the build panel's behavior (Toggle, Keep Visible, Show On Error, and Hidden) will automatically show or hide the build panel at certain points. It would be nice to have a "Manual" setting which tells `atom-build` to never automatically show or hide the build panel, allowing the user to manually show and hide it at their discretion.

**Comment by noseglid** [comment] 2016-11-08 17:34
So, this is actually a duplicate of #103

**Closed by noseglid** 2016-11-08 17:34 UTC
Labels: enhancement
